//Classes that will be displayed
let classes = [
    {
        "id": 1,
        "subject": "Football",
        "location": "Ta Qali",
        "price": 7,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/football-classes.jpg",
        "description": "Fun football sessions to keep your child active whilst having fun, coached by UEFA C Licensed coaches.",
    },
    {
        "id": 2,
        "subject": "Drama Class",
        "location": "Pieta",
        "price": 5,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/drama-classes.jpg",
        "description": "Improve your son/daughter's social skills and confidence by sending them to our drama classes. Guaranteed fun!",
    },{
        "id": 3,
        "subject": "Art Class",
        "location": "Rabat",
        "price": 4,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/art-classes.jpg",
        "description": "Let your son/daughter express their talents in art by signing them up for out lessons.",
    },{
        "id": 4,
        "subject": "Music Class",
        "location": "Iklin",
        "price": 5,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/music-classes.jpg",
        "description": "“Music is the wine that fills the cup of silence.” Send your son/daughter to our music classes to learn about music.",
    },{
        "id": 5,
        "subject": "Basketball",
        "location": "Swieqi",
        "price": 6,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/basketball-classes.jpg",
        "description": "Basketball sessions to keep your child active whilst developing their skills.",
    },{
        "id": 6,
        "subject": "Scouts",
        "location": "Saint Julian's",
        "price": 4,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/scouts-classes.jpg",
        "description": "Sign your child up for physical, mental and spiritual development, so that they'll play constructive roles in society in the future.",
    },{
        "id": 7,
        "subject": "Tennis",
        "location": "Marsa",
        "price": 10,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/tennis-classes.jpg",
        "description": "Tennis training in small groups to develop your child's tennis abilities, whilst having a lot of fun.",
    },{
        "id": 8,
        "subject": "Judo",
        "location": "Pembroke",
        "price": 7,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/judo-classes.jpg",
        "description": "Self-defense is vital, possibly saving lives. A martial art like Judo will teach self-defense, whilst increasing self-confidence.",
    },{
        "id": 9,
        "subject": "Swimming",
        "location": "Gzira",
        "price": 8,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/swimming-classes.jpg",
        "description": "Keep your child active by signing him/her up to swimming lessons. These lessons take place in heated pools during winters and outdoors during summer.",
    },{
        "id": 10,
        "subject": "Handball",
        "location": "Msida",
        "price": 7,
        "maximumSpaces": 5,
        "availableSpaces": 5,
        "image": "images/handball-classes.jpg",
        "description": "Handball is a great way to make new friends whilst staying active. Sign your child up for our lessons now!",
    },
]
